shop419/cart/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('cart/', views.viewCart, name = 'view_cart'),
    path('cart/add/<int:product_id>', views.addToCart, name = 'add_to_cart' ),
    path('cart/remove/<int:cart_item_id>', views.remFromCart, name = 'remove_from_cart'),
    path('cart/add/<int:cart_item_id>/', views.addQuantity, name='add_quantity'),
    path('cart/remove/<int:cart_item_id>/', views.remQuantity, name='rem_quantity'),
]

shop419/mainapp/urls.py
from django.urls import path
from .views import AddProduct, DeleteProduct, ProductDetails, UpdateProduct, homeView, aboutView, contactsView, searchView

urlpatterns = [
    path("", homeView, name="home"),
    path("about", aboutView, name="aboutpage"),
    path("contacts", contactsView, name="contactpage"),

    path("products/add", AddProduct.as_view(), name = "addproduct"),                  # C
    path("products/<int:pk>", ProductDetails.as_view(), name = "prod_details"),        # R
    path("products/edit/<int:pk>", UpdateProduct.as_view(), name = "edit_prod"),    # U
    path("products/del/<int:pk>", DeleteProduct.as_view(), name = "del_prod") ,      # D


    # search path
    path('products/search', searchView, name = 'search')
]

shop419/shop419/urls.py
from django.contrib import admin
from django.urls import path, include

#adding this line to support hosting of static files
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('cart/',include('cart.urls')),
    path('auth/', include('authentication.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
# the following line allows us to use the given media path during development
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop419/mainapp/models.py
from django.db import models

# Create your models here.
# ant time we make any changea in the class definations, espacially hte variables,
# we need to run tow commands.
# 

class Product(models.Model):
    # list out all the project variables below and intialize with certian Classes.

    name = models.CharField(max_length=100)
    price = models.PositiveBigIntegerField(null=False)
    desc = models.TextField()
    pic = models.ImageField(upload_to="products/", null = False)
    stock = models.PositiveBigIntegerField(default = 1)

shop419/mainapp/views.py
from unittest import result
from django.shortcuts import render
from .models import Product



# importing url resoution tools
from django.urls import reverse, reverse_lazy


# to help to load template file
from django.template import loader

# to help return HTTP response to the user for any given request 
from django.http import HttpResponse

# importing the generic calss based viwes for CRUD operations

from django.views.generic import CreateView, DeleteView, UpdateView, DeleteView

# Create your views here.
def homeView(request):
    products = Product.objects.all()
    context = {
        'product_list' : products,
        'current_page' : 'home'
    }
    template = loader.get_template('home.html')
    return HttpResponse(template.render(context, request))

def aboutView(request):
    context = {
        'current_page' : 'about'
    }
    template = loader.get_template('about.html')
    return HttpResponse(template.render(context, request))

def contactsView(request):
    context = {
        'current_page' : 'view'
    }
    template = loader.get_template('contacts.html')
    return HttpResponse(template.render(context, request))

class AddProduct(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'pic', 'stock']
    template_name = 'addproduct.html'
    success_url = reverse_lazy('home')

# read -> show details of each product
class ProductDetails(DeleteView):
    model = Product
    template_name = 'prod_details.html'
    context_object_name = 'prod'

# update ->
class UpdateProduct(UpdateView):
    model = Product
    fields = '__all__'
    template_name = 'editProduct.html'


    def det_success_url(self):
        return reverse('prod_details', kwargs = {'pk' : self.object.pk})

# Delete
class DeleteProduct(DeleteView):
    model = Product
    template_name = 'delproduct.html'
    success_url = reverse_lazy('homepage')

# search result
def searchView(request):
    query=request.GET.get('search_text')
    #fetch the query text from GET request

    result = Product.objects.filter(name__icontains = query)
    #collect the product object matching the name 
    #this runs 'SELECT' * FROM product WHERE name like '%<query>%';
    #icontains is case-insenitive
    #contains can be used for case-sensitive

    context = {
        'items'  : result,
        'query' : query
    }
    template = loader.get_template('searchResults.html')
    return HttpResponse(template.render(context,request))

shop419/mainapp/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
About
{% endblock %}

{% block content %}

     <ul>
        {% for student in students %}
            <li>{{student}}</li>
        {% endfor %}
     </ul>

    <!-- conditional -->
     {% if slept %}
     I slept
     {% else %}
     Did not slept
     {% endif %}
     
{% endblock %}

shop419/mainapp/templates/addproduct.html
{% extends 'base.html' %}

{% block title %}
Add Product
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name : </label>
        {{form.name}}
    </div>
    <div class="form-group">
        <label for="id_price">Price : </label>
        {{form.price}}
    </div>
    <div class="form-group">
        <label for="id_desc">Description : </label>
        {{form.desc}}
    </div>
    <div class="form-group">
        <label for="id_stock">Stock : </label>
        {{form.stock}}
    </div>
    <div class="form-group">
        <label for="id_pic">Pic : </label>
        {{form.pic}}
    </div>
    <button type="submit">Add Product</button>

</form>
{% endblock %}

shop419/mainapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- linking favicon -->
  <link rel="shortcut icon" href="{% static 'image/icons/new.ico' %}" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
    <script>src="{% static 'js/script.js' %}"</script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body>
  <header class="position-fixed top-0 start-0 end-0">
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{% static 'image/logo/nike1.png' %}" alt="Logo" width="30"
            height="24" class="d-inline-block align-text-top">Shoping site</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'aboutpage' %}">about</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>




            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                For more
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Details</a></li>
                <li><a class="dropdown-item" href="#">Product</a></li>
                <li><a class="dropdown-item" href="#">About</a></li>
              </ul>

              {% if user.is_authenticated %}
              {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'addproduct' %}">Add Product</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'view_cart' %}">my Cart</a>
            </li>
            {% endif %}
            {% endif %}
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search" method="get" action="{% url 'search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_text"
              value="{{query}}">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="nav-link">Logout</button>
              </form>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link text-info" aria-current="page" href="{% url 'signin' %}">Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-info" aria-current="page" href="{% url 'signup' %}">register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>
  <footer class="position-fixed bottom-0 start-0 end-0 text- center bg-secondary-subtle">
    <center> &copy; 2021 shoping site</center>
    <div class="card">
      <div class="card-header">
        <center> 🛍 “Style is a way to say who you are without having to speak.” – Rachel Zoe</center>

      </div>
    </div>
  </footer>
</body>

</html>

shop419/mainapp/templates/contacts.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrekTrend</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'images\icons\crop-backremove.ico' %}" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary"data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="">
                    <img src="{% static 'images\logos\Borcelle Shoes.png' %}" alt="Bootstrap" width="30" height="24">
                  </a>
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>
    <main>
<h1>TrekTrend</h1>
    </main>
    <footer class="position-fixed bottom-0 start-0 end-0 text-center bg-secondary-subtle">
&copy;2025
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

shop419/mainapp/templates/delproduct.html
{% extends 'base.html' %}
{% block title %}
Delete Product
{% endblock %}

{% block content %}
<div class="text-center">
    <p>
        The product : {{product.name}} will be deleted...
    </p>
</div>
<form method="post" enctype="multipart/form-data" class="form text-center">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Confirm delete</button>
    <a href="{% url 'prod_details' product.pk %}">Cancel</a>

</form>
{% endblock %}

shop419/mainapp/templates/editProduct.html
{% extends 'base.html' %}
{% block title %}
edit
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Add Product</button>
</form>

{% endblock %}

shop419/mainapp/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- This is for home page -->
        <div class="container">
            {% for product in product_list %}
            <div class="card">
                <div class="card-img">
                    <img src="{{product.pic}}" alt="">
                </div>
                <div class="card-text">
                    <h3>{{product.name}}</h3>
                    <h5>Price : <ins>{{product.price}}</ins></h5>
                    <h7>Stock : {{product.stock}}</h7>
                    <p>
                        {{product.desc}}
                    </p>
                    <button>Add to cart</button>
                </div>
            </div>
            {% endfor %}
        </div>
<!-- home page code ends -->
 {% endblock %}

shop419/mainapp/templates/prod_details.html
{% extends 'base.html' %} 
{% block title %} 
{{ prod.name }} 
{% endblock %} 
    {% block content %}
    <div class="row">
      <div class="col-sm-6">
        <img src="{{prod.pic.url}}" class="w-100 h-100" alt="" />
      </div>
      <div class="col-sm-6">
        <div class="row">
          <h1>{{ prod.name }}</h1>
          <p>Rs.{{ prod.price }}</p>
        </div>
        <div class="row">
          {% if user.is_staff %}
          <a href="{% url 'edit_prod' prod.pk %}" class="btn btn-secondary"
            >Edit Product</a
          >
          <a href="{% url 'del_prod' prod.pk %}" class="btn btn-secondary"
            >Delete to Cart</a
          >
          {% else %}
          <a href="" class="btn btn-secondary">Add to Cart</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endblock %}

shop419/mainapp/templates/searchResults.html
{% extends 'base.html' %}

{% block title %}
search | {{query}}
{% endblock %}

{% block content %}

<h2>search result for {{query}}</h2>

        <div class="container">
            {% for product in items %}
            <div class="card">
                <div class="card-img">
                    <img src="{{product.pic.url}}" alt="">
                </div>
                <div class="card-text">
                    <h3>
                        <a href="{% url 'prod_details' product.id %}">
                        {{product.name}}</a></h3>
                    <h5>Price : <ins>{{product.price}}</ins></h5>
                    <h7>Stock : {{product.stock}}</h7>
                    <p>
                        {{product.desc}}
                    </p>
                    <button>Add to cart</button>
                </div>
            </div>
            {% endfor %}
        </div>

 {% endblock %}